branches:
  except:
    - gh-pages

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5-dev"

install: "pip install oauthlib tornado<4.3 toro"

script: "python setup.py test"

notifications:
  slack: targetprocess:3vskJskCGoKESMxPoIPRaOkd