branches:
  except:
    - gh-pages

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5-dev"

install: "python setup.py install"

script: "python setup.py test"

notifications:
  slack: targetprocess:3vskJskCGoKESMxPoIPRaOkd